#!/usr/bin/env bash
set -ex

export PGDATABASE=$2

ninja
./real/memory
./real/writes

time psql -c "$1" > /dev/null
time psql -A -c "$1" > /dev/null

time ./real/select.endl "$1" > /dev/null

time ./real/select.simple "$1" > /dev/null

time ./real/select.unbuffered "$1" > /dev/null

time ./real/select.buffer "$1" > /dev/null

# time ./real/select.to_chars "$1" > /dev/null

time ./real/fast "$1" > /dev/null

time ./libs/pgasio/examples/pg-asio-csj -d "${PGDATABASE}" "$1" > /dev/null
